### ISSUE TITLE
Feature request : horizontal scroll

### ISSUE THREAD

**Issue by reind33r** [jarnokurlin/fullcalendar#5]
Hi!

I needed a ressource timeline view for a day organization and I found your fork of fullcalendar. It was perfect but no possibility to scroll horizontally. First I added the following css :

``` css
// Modified
.fc-view {
    width: 100%; /* needed for view switching (when view is absolute) */
    overflow: hidden;
    overflow-x: scroll; // Here is the interesting line
    }

// Added at the end
#yourSelector table { table-layout: fixed; }
// In order to have a fixed width and a padding in head cells, not required
table.fc-border-separate, table.fc-border-separate.fc td, .fc th {
width: 100px !important;
padding: 5px 3px;
}
```

So I worked on the production javascript and I modified the following function like this (line 4948) :

``` js
function buildSkeleton(maxRowCnt, showNumbers) {
    [...]
    s =
        "<div style='position: relative; margin-top: -10px;'>" +
        "<table class='fc-border-separate' style='width:100%' cellspacing='0'>" +
            [...]
        "</table>" +
        "</div>";
```

I just added a div which wrap the table, and put a -10px margin-top to make the events displayed correctly. And now events set or created out of the "normal" display frame (I mean with scrolling to see them) are displayed correctly.

(Sorry If I don't post in the right place, I don't really know GitHub. Fell free to indicate me where it should be and how my comments would me the most helpful to you. I also want to add that it might be a bad solution, but it seems to work as I expect)
